class_weight: balanced
early_stopping: true
l2_regularization: 1.2552381981291005
learning_rate: 0.41416567289195627
max_bins: 211
max_depth: 14
max_iter: 116
max_leaf_nodes: 26
validation_fraction: 0.5
verbose: 0
