class_weight: balanced
early_stopping: true
l2_regularization: 7.234651778309412
learning_rate: 0.00019842771375626586
max_bins: 123
max_depth: 5
max_iter: 27
max_leaf_nodes: 69
validation_fraction: 0.5
verbose: 0
