class_weight: balanced
early_stopping: true
l2_regularization: 1.2439994726017867
learning_rate: 0.18368854944799645
max_bins: 210
max_depth: 7
max_iter: 107
max_leaf_nodes: 53
validation_fraction: 0.5
verbose: 0
