class_weight: balanced
early_stopping: true
l2_regularization: 7.488038825386118
learning_rate: 0.10189444514272937
max_bins: 248
max_depth: 3
max_iter: 17
max_leaf_nodes: 66
validation_fraction: 0.5
verbose: 0
