class_weight: balanced
early_stopping: true
l2_regularization: 1.8591123209017923
learning_rate: 0.2474481053349085
max_bins: 203
max_depth: 8
max_iter: 145
max_leaf_nodes: 63
validation_fraction: 0.5
verbose: 0
