class_weight: balanced
early_stopping: true
l2_regularization: 4.130003988473892
learning_rate: 0.689204678859507
max_bins: 173
max_depth: 4
max_iter: 145
max_leaf_nodes: 66
validation_fraction: 0.5
verbose: 0
