class_weight: balanced
early_stopping: true
l2_regularization: 0.7562206659513693
learning_rate: 0.0026540663379838693
max_bins: 184
max_depth: 7
max_iter: 25
max_leaf_nodes: 27
validation_fraction: 0.5
verbose: 0
