class_weight: balanced
early_stopping: true
l2_regularization: 4.3532239261827685
learning_rate: 0.005016260922153408
max_bins: 135
max_depth: 13
max_iter: 74
max_leaf_nodes: 24
validation_fraction: 0.5
verbose: 0
