class_weight: balanced
early_stopping: true
l2_regularization: 4.902826208823848
learning_rate: 0.2337028150701688
max_bins: 183
max_depth: 2
max_iter: 36
max_leaf_nodes: 42
validation_fraction: 0.5
verbose: 0
