class_weight: balanced
early_stopping: true
l2_regularization: 5.8189487687999195
learning_rate: 0.482543812461006
max_bins: 194
max_depth: 7
max_iter: 78
max_leaf_nodes: 94
validation_fraction: 0.5
verbose: 0
