class_weight: balanced
early_stopping: true
l2_regularization: 5.10827605197663
learning_rate: 0.014064095930498321
max_bins: 178
max_depth: 10
max_iter: 133
max_leaf_nodes: 58
validation_fraction: 0.5
verbose: 0
