class_weight: balanced
early_stopping: true
l2_regularization: 1.7338118411792236
learning_rate: 0.03209893856511013
max_bins: 96
max_depth: 2
max_iter: 176
max_leaf_nodes: 12
validation_fraction: 0.5
verbose: 0
