class_weight: balanced
early_stopping: true
l2_regularization: 0.7167060319835361
learning_rate: 0.014466717064539343
max_bins: 31
max_depth: 4
max_iter: 141
max_leaf_nodes: 89
validation_fraction: 0.5
verbose: 0
