class_weight: balanced
early_stopping: true
l2_regularization: 0.9333366848076785
learning_rate: 0.0006080146237029431
max_bins: 67
max_depth: 6
max_iter: 108
max_leaf_nodes: 84
validation_fraction: 0.5
verbose: 0
