class_weight: balanced
early_stopping: true
l2_regularization: 0.3398589307200095
learning_rate: 0.20043953572385406
max_bins: 94
max_depth: 13
max_iter: 119
max_leaf_nodes: 39
validation_fraction: 0.5
verbose: 0
