class_weight: balanced
early_stopping: true
l2_regularization: 1.5510911997021637
learning_rate: 0.010851038249384251
max_bins: 245
max_depth: 12
max_iter: 168
max_leaf_nodes: 85
validation_fraction: 0.5
verbose: 0
