class_weight: balanced
early_stopping: true
l2_regularization: 4.679576744735479
learning_rate: 0.004574182636876318
max_bins: 55
max_depth: 10
max_iter: 74
max_leaf_nodes: 33
validation_fraction: 0.5
verbose: 0
