class_weight: balanced
early_stopping: true
l2_regularization: 4.093125176701749
learning_rate: 0.03252069292839071
max_bins: 161
max_depth: 6
max_iter: 175
max_leaf_nodes: 47
validation_fraction: 0.5
verbose: 0
