class_weight: balanced
early_stopping: true
l2_regularization: 7.222236521541415
learning_rate: 0.03353119972419962
max_bins: 143
max_depth: 7
max_iter: 179
max_leaf_nodes: 22
validation_fraction: 0.5
verbose: 0
