class_weight: balanced
early_stopping: true
l2_regularization: 2.842129987402895
learning_rate: 0.04318694866681628
max_bins: 136
max_depth: 7
max_iter: 199
max_leaf_nodes: 18
validation_fraction: 0.5
verbose: 0
