class_weight: balanced
early_stopping: true
l2_regularization: 3.605008362562857
learning_rate: 0.1802537795705461
max_bins: 162
max_depth: 5
max_iter: 175
max_leaf_nodes: 61
validation_fraction: 0.5
verbose: 0
