class_weight: balanced
early_stopping: true
l2_regularization: 4.4446949597180305
learning_rate: 0.7196890625380392
max_bins: 152
max_depth: 7
max_iter: 133
max_leaf_nodes: 34
validation_fraction: 0.5
verbose: 0
