class_weight: balanced
early_stopping: true
l2_regularization: 7.796910002727692
learning_rate: 0.0028887267528938205
max_bins: 51
max_depth: 12
max_iter: 94
max_leaf_nodes: 16
validation_fraction: 0.5
verbose: 0
