class_weight: balanced
early_stopping: true
l2_regularization: 8.556209483356476
learning_rate: 0.5907671963523932
max_bins: 231
max_depth: 3
max_iter: 185
max_leaf_nodes: 71
validation_fraction: 0.5
verbose: 0
