class_weight: balanced
early_stopping: true
l2_regularization: 5.965820088990672
learning_rate: 0.00015413695928472268
max_bins: 60
max_depth: 11
max_iter: 153
max_leaf_nodes: 42
validation_fraction: 0.5
verbose: 0
