class_weight: balanced
early_stopping: true
l2_regularization: 3.270852010814347
learning_rate: 0.0006145948890791072
max_bins: 68
max_depth: 6
max_iter: 139
max_leaf_nodes: 75
validation_fraction: 0.5
verbose: 0
