class_weight: balanced
early_stopping: true
l2_regularization: 0.7116501308371925
learning_rate: 0.0002607828269019215
max_bins: 238
max_depth: 7
max_iter: 48
max_leaf_nodes: 76
validation_fraction: 0.5
verbose: 0
