class_weight: balanced
early_stopping: true
l2_regularization: 1.3382952895927658
learning_rate: 0.00010976381676841366
max_bins: 156
max_depth: 10
max_iter: 128
max_leaf_nodes: 56
validation_fraction: 0.5
verbose: 0
