class_weight: balanced
early_stopping: true
l2_regularization: 1.9411562178234698
learning_rate: 0.000504721478528024
max_bins: 107
max_depth: 3
max_iter: 82
max_leaf_nodes: 93
validation_fraction: 0.5
verbose: 0
