class_weight: balanced
early_stopping: true
l2_regularization: 1.4729552799844858
learning_rate: 0.0010269486605666925
max_bins: 187
max_depth: 12
max_iter: 169
max_leaf_nodes: 38
validation_fraction: 0.5
verbose: 0
