class_weight: balanced
early_stopping: true
l2_regularization: 4.51699081148222
learning_rate: 0.00013540770290321755
max_bins: 212
max_depth: 5
max_iter: 83
max_leaf_nodes: 11
validation_fraction: 0.5
verbose: 0
