class_weight: balanced
early_stopping: true
l2_regularization: 4.23432978900535
learning_rate: 0.06391526094648306
max_bins: 152
max_depth: 4
max_iter: 194
max_leaf_nodes: 69
validation_fraction: 0.5
verbose: 0
