class_weight: balanced
early_stopping: true
l2_regularization: 3.1748822495391438
learning_rate: 0.5547119003771779
max_bins: 131
max_depth: 3
max_iter: 194
max_leaf_nodes: 89
validation_fraction: 0.5
verbose: 0
