class_weight: balanced
early_stopping: true
l2_regularization: 5.3085569155559895
learning_rate: 0.2549028380630404
max_bins: 135
max_depth: 12
max_iter: 107
max_leaf_nodes: 7
validation_fraction: 0.5
verbose: 0
