class_weight: balanced
early_stopping: true
l2_regularization: 1.6424728481167827
learning_rate: 0.06968729303708451
max_bins: 118
max_depth: 6
max_iter: 7
max_leaf_nodes: 24
validation_fraction: 0.5
verbose: 0
