class_weight: balanced
early_stopping: true
l2_regularization: 7.757529055931681
learning_rate: 0.001184077455160496
max_bins: 141
max_depth: 8
max_iter: 133
max_leaf_nodes: 29
validation_fraction: 0.5
verbose: 0
