class_weight: balanced
early_stopping: true
l2_regularization: 1.109863248582068
learning_rate: 0.2043567651097985
max_bins: 186
max_depth: 9
max_iter: 142
max_leaf_nodes: 7
validation_fraction: 0.5
verbose: 0
