class_weight: balanced
early_stopping: true
l2_regularization: 4.914956388244511
learning_rate: 0.16422185597645048
max_bins: 96
max_depth: 4
max_iter: 164
max_leaf_nodes: 18
validation_fraction: 0.5
verbose: 0
