class_weight: balanced
early_stopping: true
l2_regularization: 8.579456176227568
learning_rate: 0.013815692718603336
max_bins: 134
max_depth: 5
max_iter: 119
max_leaf_nodes: 66
validation_fraction: 0.5
verbose: 0
