class_weight: balanced
early_stopping: true
l2_regularization: 3.7590487429979924
learning_rate: 0.0007123865242006193
max_bins: 252
max_depth: 7
max_iter: 65
max_leaf_nodes: 42
validation_fraction: 0.5
verbose: 0
