class_weight: balanced
early_stopping: true
l2_regularization: 6.464233413947035
learning_rate: 0.001304998175447199
max_bins: 252
max_depth: 12
max_iter: 18
max_leaf_nodes: 25
validation_fraction: 0.5
verbose: 0
