class_weight: balanced
early_stopping: true
l2_regularization: 3.086167800843861
learning_rate: 0.0007427372557445707
max_bins: 156
max_depth: 3
max_iter: 123
max_leaf_nodes: 71
validation_fraction: 0.5
verbose: 0
