class_weight: balanced
early_stopping: true
l2_regularization: 3.098513327874074
learning_rate: 0.00039528594734737876
max_bins: 89
max_depth: 5
max_iter: 116
max_leaf_nodes: 33
validation_fraction: 0.5
verbose: 0
