class_weight: balanced
early_stopping: true
l2_regularization: 7.340626048404454
learning_rate: 0.04186840135025379
max_bins: 99
max_depth: 11
max_iter: 187
max_leaf_nodes: 42
validation_fraction: 0.5
verbose: 0
