class_weight: balanced
early_stopping: true
l2_regularization: 1.0765667993596795
learning_rate: 0.3034971314297936
max_bins: 56
max_depth: 12
max_iter: 108
max_leaf_nodes: 81
validation_fraction: 0.5
verbose: 0
