class_weight: balanced
early_stopping: true
l2_regularization: 6.651954569952129
learning_rate: 0.0024329577066915364
max_bins: 208
max_depth: 13
max_iter: 58
max_leaf_nodes: 48
validation_fraction: 0.5
verbose: 0
