class_weight: balanced
early_stopping: true
l2_regularization: 0.4006416454400541
learning_rate: 0.38417157138665825
max_bins: 190
max_depth: 13
max_iter: 86
max_leaf_nodes: 86
validation_fraction: 0.5
verbose: 0
