class_weight: balanced
early_stopping: true
l2_regularization: 9.915074670186842
learning_rate: 0.004352247373312767
max_bins: 87
max_depth: 9
max_iter: 132
max_leaf_nodes: 17
validation_fraction: 0.5
verbose: 0
