class_weight: balanced
early_stopping: true
l2_regularization: 8.91603438277764
learning_rate: 0.0014919744222164188
max_bins: 228
max_depth: 6
max_iter: 170
max_leaf_nodes: 56
validation_fraction: 0.5
verbose: 0
