class_weight: balanced
early_stopping: true
l2_regularization: 8.242742305909816
learning_rate: 0.28505846868400997
max_bins: 187
max_depth: 13
max_iter: 69
max_leaf_nodes: 20
validation_fraction: 0.5
verbose: 0
