class_weight: balanced
early_stopping: true
l2_regularization: 4.884111887948292
learning_rate: 0.0007341306685581474
max_bins: 221
max_depth: 11
max_iter: 191
max_leaf_nodes: 18
validation_fraction: 0.5
verbose: 0
