class_weight: balanced
early_stopping: true
l2_regularization: 7.816795057236838
learning_rate: 0.010410264091630412
max_bins: 235
max_depth: 8
max_iter: 42
max_leaf_nodes: 75
validation_fraction: 0.5
verbose: 0
