class_weight: balanced
early_stopping: true
l2_regularization: 2.4058961996534878
learning_rate: 0.0002810041985954914
max_bins: 176
max_depth: 12
max_iter: 51
max_leaf_nodes: 23
validation_fraction: 0.5
verbose: 0
