class_weight: balanced
early_stopping: true
l2_regularization: 8.626501519222474
learning_rate: 0.0030094300221607637
max_bins: 82
max_depth: 8
max_iter: 121
max_leaf_nodes: 40
validation_fraction: 0.5
verbose: 0
