class_weight: balanced
early_stopping: true
l2_regularization: 0.9692170943916412
learning_rate: 0.008888077848496658
max_bins: 167
max_depth: 13
max_iter: 134
max_leaf_nodes: 24
validation_fraction: 0.5
verbose: 0
