class_weight: balanced
early_stopping: true
l2_regularization: 5.86518526806177
learning_rate: 0.0362602106209582
max_bins: 82
max_depth: 13
max_iter: 189
max_leaf_nodes: 17
validation_fraction: 0.5
verbose: 0
