class_weight: balanced
early_stopping: true
l2_regularization: 1.1280624385619764
learning_rate: 0.0006168323170179721
max_bins: 58
max_depth: 5
max_iter: 174
max_leaf_nodes: 30
validation_fraction: 0.5
verbose: 0
