class_weight: balanced
early_stopping: true
l2_regularization: 7.050303018637387
learning_rate: 0.003890267002767105
max_bins: 224
max_depth: 10
max_iter: 9
max_leaf_nodes: 39
validation_fraction: 0.5
verbose: 0
