class_weight: balanced
early_stopping: true
l2_regularization: 1.3813168747631954
learning_rate: 0.00024009385611953367
max_bins: 190
max_depth: 5
max_iter: 100
max_leaf_nodes: 42
validation_fraction: 0.5
verbose: 0
